package parser;

enum NodeType {
    PRIMARY_EXPR, ID_EXPR, POSTFIX_EXPR, UNARY_EXPR, CAST_EXPR, PM_EXPR, BINARY_EXPR, CONDITIONAL_EXPR, ASSIGNMENT_EXPR, COMMA_EXPR,

    LABELED_STMT, EXPRESSION_STMT, COMPOUND_STMT, IF_STMT, IF_ELSE_STMT, FOR_STMT, WHILE_STMT, DO_STMT, BREAK_STMT, CONTINUE_STMT, GOTO_STMT
}